---
title: Bootrace
hero_image: images/small_banner.png
description: Maak een bootrace-spel waarin je obstakels moet ontwijken
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Inleiding
  completion: engaged
- title: Aan de slag
- title: De boot besturen
- title: Botsen!
- title: Winnen!
- title: 'Uitdaging: geluidseffecten'
  challenge: true
- title: Een meting toevoegen
  completion: internal
- title: Obstakels en versnellers
- title: 'Uitdaging: verbeter je spel'
  challenge: true
- title: Wat nu?
