---
title: Bootrace
hero_image: images/small_banner.png
description: Maak een bootrace-spel waarin je obstakels moet ontwijken
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Aan de slag
  - 
    title: De boot besturen
    completion:
      - engaged
  - 
    title: Botsen!
  - 
    title: Winnen!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
