---
title: नौका रेस
hero_image: images/small_banner.png
description: एक नौका रेस गेम बनाएँ जिसमें आपको रुकावटों से बचना होता है।
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
duration: 2
interests: games
technology: scratch
site_areas: codeclub, scratch
steps:
- title: भूमिका
- title: आपको क्या चाहिए होगा
- title: आरंभ करना
- title: नौका को नियंत्रित करना
- title: टकरा जाना
- title: 'चुनौती: जीत!'
- title: 'चुनौती: ध्वनि प्रभाव'
- title: टाइम ट्रायल
- title: रुकावटें और पॉवर अप
- title: 'चुनौती: अधिक रुकावटें!'
- title: 'चुनौती: और बोट्स!'
- title: 'चुनौती: और लेवल!'

