---
title: ボートレース
hero_image: images/small_banner.png
description: 障害物を避けるボートレースを作成する
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: はじめに
- title: はじめましょう
- title: ボートの制御
  completion:
  - engaged
- title: ぶつかった！
- title: 勝利！
- title: チャレンジ：効果音
  challenge: true
- title: タイマーの追加
- title: 障害物とブースター
  completion:
  - internal
- title: チャレンジ：ゲームをより良くする
  challenge: true