---
title: Corrida de Barcos
hero_image: images/small_banner.png
description: Cria um jogo de corrida de barcos em que terás de evitar obstáculos
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Guia de Introdução
  - 
    title: Controlar o barco
    completion:
      - engaged
  - 
    title: Colisão!
  - 
    title: Vencer!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
