---
title: 划船比赛
hero_image: images/small_banner.png
description: 制作一个划船比赛游戏，在游戏中，你需要避开障碍。
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: 简介
  - 
    title: 开始
  - 
    title: 控制赛艇
  - 
    title: 撞击!
  - 
    title: 撞击
  - 
    title: '挑战: 音效'
    challenge: true
  - 
    title: 添加计时器
  - 
    title: 计时赛
  - 
    title: '障碍和助力'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
