---
title: Venekilpailu
hero_image: images/small_banner.png
description: Luo venekilpailu peli, jossa sinun on väistettävä esteitä
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Esittely
  completion: engaged
- title: Näin pääset alkuun
- title: Veneen ohjaaminen
- title: Törmääminen!
- title: Voittaminen!
- title: 'Haaste: äänitehosteet'
  challenge: true
- title: Ajastimen lisääminen
  completion: internal
- title: Esteet ja lisävoimat
- title: 'Haaste: pelin parantaminen'
  challenge: true
- title: Mitä seuraavaksi?
