---
title: Venekilpailu
hero_image: images/small_banner.png
description: Luo venekilpailu peli, jossa sinun on väistettävä esteitä
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Näin pääset alkuun
  - 
    title: Veneen ohjaaminen
    completion:
      - engaged
  - 
    title: Törmääminen!
  - 
    title: Voittaminen!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
