---
title: Venekilpailu
hero_image: images/small_banner.png
description: Luo venekilpailu peli, jossa sinun on väistettävä esteitä
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Esittely
- title: Näin pääset alkuun
- title: Veneen ohjaaminen
  completion:
  - engaged
- title: Törmääminen!
- title: Voittaminen!
- title: 'Haaste: äänitehosteet'
  challenge: true
- title: Ajastimen lisääminen
- title: Esteet ja lisävoimat
  completion:
  - internal
- title: 'Haaste: pelin parantaminen'
  challenge: true