---
title: Carrera de Barcos
hero_image: images/small_banner.png
description: Haz un juego de carreras de barcos en el que tendrás que evitar obstáculos.
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Primeros pasos
  - 
    title: Controlando el barco
    completion:
      - engaged
  - 
    title: '¡Chocando!'
  - 
    title: '¡Ganando!'
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
