---
title: Carrera de Barcos
hero_image: images/small_banner.png
description: Haz un juego de carreras de barcos en el que tendrás que evitar obstáculos.
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Introducción
  completion: engaged
- title: Primeros pasos
- title: Controlando el barco
- title: "¡Chocando!"
- title: "¡Ganando!"
- title: 'Desafío: efectos de sonido'
  challenge: true
- title: Añadir un temporizador
  completion: internal
- title: Obstáculos y mejoras
- title: 'Desafío: mejora tu juego'
  challenge: true
- title: "¿Qué sigue?"
