---
title: Ras Cwch
hero_image: images/small_banner.png
description: Byddwn yn creu gêm i hwylio cwch at ynys yng nghanol y môr.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: games
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Dechrau'r prosiect
  - 
    title: Rheoli'r cwch
  - 
    title: Llongddrylliad!
  - 
    title: 'Her: Ennill!'
  - 
    title: 'Her: Effeithiau sain'
  - 
    title: 'Ras yn erbyn amser'
  - 
    title: Rhwystrau a chyflymu'r cwch
  - 
    title: 'Her: Mwy o rwystrau!'
  - 
    title: 'Her: Mwy o gychod!'
  - 
    title: 'Her: Mwy o lefelau!'
  - 
    title: 'Challenge: more levels!'
