---
title: Ras gwch
hero_image: images/small_banner.png
description: Creu gêm rasio cwch lle mae angen osgoi rhwystrau
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Dechrau'r prosiect
  - 
    title: Rheoli'r cwch
    completion:
      - engaged
  - 
    title: Llongddrylliad!
  - 
    title: Ennill!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
