---
title: Ras gwch
hero_image: images/small_banner.png
description: Creu gêm rasio cwch lle mae angen osgoi rhwystrau
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Cyflwyniad
  completion: engaged
- title: Dechrau'r prosiect
- title: Rheoli'r cwch
- title: Llongddrylliad!
- title: Ennill!
- title: 'Her: effeithiau sain'
  challenge: true
- title: Ychwanegu Amserydd
  completion: internal
- title: Rhwystrau a chyflymu'r cwch
- title: 'Her: gwella dy gêm'
  challenge: true
- title: Beth nesaf?
