---
title: Cursă cu bărcuțe
hero_image: images/small_banner.png
description: Vei învăța cum să creezi un joc în care vei utiliza mouse-ul ca să navighezi o barcă înspre o insulă pustie.
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Introducere
  - 
    title: Noțiuni de bază
  - 
    title: Controlarea bărcii
  - 
    title: Accidentele!
  - 
    title: Câștigă!
  - 
    title: 'Provocare: efecte sonore'
    challenge: true
  - 
    title: Adăugarea unui cronometru
  - 
    title: Obstacole și boostere
  - 
    title: 'Provocare: îmbunătățirea jocului tău'
    challenge: true
  - 
    title: Testează-te
  - 
    title: Ce urmează?
