---
title: Boat Race
hero_image: images/small_banner.png
description: Vei învăța cum să creezi un joc în care vei utiliza mouse-ul ca să navighezi o barcă înspre o insulă pustie.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Boat Race
  - 
    title: Noţiuni de bază
  - 
    title: Controlarea barcii
  - 
    title: Accidentele!
  - 
    title: Winning!
  - 
    title: 'Provocare: efectele de sunet'
    challenge: true
  - 
    title: Adăugarea unui cronometru
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: Ce urmează?
