---
title: Corrida de barco
hero_image: images/small_banner.png
description: Crie um jogo de corrida de barcos onde você deve evitar os obstáculos
listed: true
copyedit: true
version: 4.1.2
last_tested: 20/09/2018
steps:
- title: Introdução
  completion: engaged
- title: Começando
- title: Controlando o barco
- title: Batendo!
- title: Ganhando o jogo!
- title: 'Desafio: efeitos sonoros'
  challenge: true
- title: Adicionando um cronômetro
  completion: internal
- title: Obstáculos e aceleradores
- title: 'Desafio: melhore seu jogo'
  challenge: true
- title: E agora?
