---
title: Corrida de barco
hero_image: images/small_banner.png
description: Crie um jogo de corrida de barcos onde você deve evitar os obstáculos
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Começando
  - 
    title: Controlando o barco
    completion:
      - engaged
  - 
    title: Batendo!
  - 
    title: Ganhando!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
