---
title: Corrida de barco
hero_image: images/small_banner.png
description: Crie um jogo de corrida de barcos onde você deve evitar os obstáculos
listed: true
copyedit: true
version: 4.1.2
last_tested: 20/09/2018
steps:
  - 
    title: Introdução
  - 
    title: Começando
  - 
    title: Controlando o barco
    completion:
      - engaged
  - 
    title: Batendo!
  - 
    title: Ganhando!
  - 
    title: 'Desafio: efeitos sonoros'
    challenge: true
  - 
    title: Adicionando um cronômetro
  - 
    title: Obstáculos e aceleradores
    completion:
      - internal
  - 
    title: 'Desafio: melhore seu jogo'
    challenge: true
  - 
    title: O que vem depois?
