---
title: Carreres de vaixells
hero_image: images / small_banner.png
description: Crea un joc de carreres de vaixells en el qual has d'evitar obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Introducció
  - 
    title: Per començar
  - 
    title: Control del vaixell
  - 
    title: Xocar!
  - 
    title: Guanyar!
  - 
    title: 'Repte: efectes de so'
    challenge: true
  - 
    title: Afegir un temporitzador
  - 
    title: Obstacles i potenciadors
  - 
    title: 'Repte: millorar el teu joc'
    challenge: true
  - 
    title: I ara què ve?
