---
title: Dirka s čolnom
hero_image: images/small_banner.png
description: Ustvari dirkalno igro, v kateri se boš s čolnom moral izogibati oviram
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Uvod
  completion: engaged
- title: Na začetku
- title: Upravljanje čolna
- title: Trk!
- title: Zmaga!
- title: 'Izziv: Zvočni učinki!'
  challenge: true
- title: Dodajanje časovnika
  completion: internal
- title: Ovire in pospeševalci
- title: 'Izziv: izboljšaj igro'
  challenge: true
- title: Kaj sledi?
