---
title: Boat rase
hero_image: images/small_banner.png
description: Ustvarite igro za čoln, v kateri se boste morali izogibati oviram
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Uvod
  - 
    title: Začetek
  - 
    title: Nadziranje čolna
  - 
    title: Trčenje!
  - 
    title: Uspešen!
  - 
    title: 'Izziv: Zvočni učinki!'
    challenge: true
  - 
    title: Dodajanje časovnika
  - 
    title: Ovire in ojačevalci
  - 
    title: 'Izziv: izboljšanje igre'
    challenge: true
  - 
    title: Kaj je naslednje?
