---
title: Boat race
hero_image: images/small_banner.png
description: Create a boat-racing game in which you have to avoid obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Úvod
  - 
    title: Začínáme
  - 
    title: Ovládání lodi
  - 
    title: Havárie!
  - 
    title: Winning!
  - 
    title: 'Výzva: zvukové efekty'
    challenge: true
  - 
    title: Přidání časovače
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
