---
title: Hajóverseny
hero_image: images/small_banner.png
description: Hozz létre egy olyan játékot, amelyben egy hajónak ki kell kerülnie különböző akadályokat
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Első lépések
  - 
    title: A hajó irányítása
    completion:
      - engaged
  - 
    title: Ütközés!
  - 
    title: Győzelem!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
