---
title: Carrera de botes
hero_image: imagenes/small_banner.png
description: Aprenderás cómo crear un juego en el que usarás el ratón para navegar con tu bote hasta una isla desierta
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Introducción
  - 
    title: Introducción
  - 
    title: Control del bote
  - 
    title: '¡Estrellado!'
  - 
    title: '¡Ganador!'
  - 
    title: 'Desafío: efectos de sonido'
    challenge: true
  - 
    title: Añadir un temporizador
  - 
    title: Obstáculos y potenciadores
  - 
    title: 'Desafío: mejorar el juego'
    challenge: true
  - 
    title: '¿Qué sigue?'
