---
title: سباق القوارب
hero_image: images/small_banner.png
description: أنشئ لعبة سباق القوارب حيث يجب عليك تجنب العقبات
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: المقدمة
  completion: engaged
- title: الشروع في البدء
- title: التحكم في القارب
- title: الاصطدام!
- title: الفوز!
- title: 'التحدي: المؤثرات الصوتية'
  challenge: true
- title: إضافة مؤقت
  completion: internal
- title: سباق الزمن
- title: العوائق وعمليات التشغيل
  challenge: true
- title: ما التالي؟
