---
title: Wyścig łodzi
hero_image: images/small_banner.png
description: Naucz się, jak stworzyć grę, w której będziesz kierować łodzią, żeby
  omijać przeszkody
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
- title: Wprowadzenie
- title: Zaczynamy
- title: Sterowanie łodzią
  completion:
  - engaged
- title: Zderzenia!
- title: Wygrana!
- title: 'Wyzwanie: efekty dźwiękowe'
  challenge: true
- title: Dodawanie stopera
- title: Przeszkody i przyspieszacze
  completion:
  - internal
- title: 'Wyzwanie: ulepszanie gry'
  challenge: true