---
title: Wyścig łodzi
hero_image: images/small_banner.png
description: Naucz się, jak stworzyć grę, w której będziesz kierować łodzią, żeby omijać przeszkody
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Zaczynamy
  - 
    title: Sterowanie łodzią
    completion:
      - engaged
  - 
    title: Zderzenia!
  - 
    title: Wygrana!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
