---
title: Preteky lodí
hero_image: images/small_banner.png
description: Vytvorenie hry preteky lodí, v ktorej sa musíš vyhnúť prekážkam
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Úvod
  - 
    title: Začíname
  - 
    title: Ovládanie lode
  - 
    title: Narazenie!
  - 
    title: Víťazstvo!
  - 
    title: 'Výzva: zvukové efekty'
    challenge: true
  - 
    title: Preteky na čas
  - 
    title: Prekážky a vylepšenia
  - 
    title: 'Výzva: zlepši svoju hru'
    challenge: true
  - 
    title: Čo ďalej?
