---
title: Course de bateaux
hero_image: images/small_banner.png
description: Crée un jeu de course de bateau dans lequel tu devra éviter les obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Introduction
  - 
    title: Pour commencer
  - 
    title: Contrôler le bateau
    completion:
      - engaged
  - 
    title: Collision!
  - 
    title: Victoire!
  - 
    title: 'Défi: effets sonores'
    challenge: true
  - 
    title: Ajouter un chronomètre
  - 
    title: Obstacles et boosters
    completion:
      - internal
  - 
    title: 'Défi : améliorer ton jeu'
    challenge: true
  - 
    title: Et ensuite ?
