---
title: Barca da corsa
hero_image: images/small_banner.png
description: Crea un gioco in cui una barca deve gareggiare evitando degli ostacoli
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Introduzione
  - 
    title: Per cominciare
  - 
    title: Controllare la barca
  - 
    title: Ci stiamo schiantando!
  - 
    title: Vittoria!
  - 
    title: 'Sfida: Abilitare gli effetti sonori'
    challenge: true
  - 
    title: Aggiungere un timer
  - 
    title: Ostacoli e potenziamenti
  - 
    title: 'Sfida: migliora il tuo gioco'
    challenge: true
  - 
    title: E poi?
