---
title: Barca da corsa
hero_image: images/small_banner.png
description: Crea un gioco in cui una barca deve gareggiare evitando degli ostacoli
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Per cominciare
  - 
    title: Controllare la barca
    completion:
      - engaged
  - 
    title: Ci stiamo schiantando!
  - 
    title: Vittoria!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
