---
title: Tekne yarışı
hero_image: images/small_banner.png
description: Engellerden kaçınmanız gereken bir tekne yarış oyunu oluşturun
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Giriş
  - 
    title: Başlarken
  - 
    title: Tekneyi kontrol etme
    completion:
      - engaged
  - 
    title: Çarpışma!
  - 
    title: Kazanan!
  - 
    title: 'Challenge: ses efektleri'
    challenge: true
  - 
    title: Zamanlayıcı eklemek
  - 
    title: Engeller ve güçlendiriciler
    completion:
      - internal
  - 
    title: 'Zorluk: oyununuzu geliştirmek'
    challenge: true
  - 
    title: Sırada ne var?
