---
title: Tekne yarışı
hero_image: images/small_banner.png
description: Engellerden kaçınmanız gereken bir tekne yarış oyunu oluşturun
listed: true
copyedit: true
version: 4.1.2
last_tested: 2024-11-19
steps:
  - 
    title: What you will make
  - 
    title: Başlarken
  - 
    title: Tekneyi kontrol etme
    completion:
      - engaged
  - 
    title: Çarpışma!
  - 
    title: Kazanan!
  - 
    title: Adding a timer
    completion:
      - internal
  - 
    title: Obstacles and boosters
  - 
    title: Challenge
    challenge: true
    completion:
      - external
  - 
    title: What can you do now?
